name: Docker Image CI

on:
  push:
    branches: [ "main" ]
 

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build and run Docker container
      run: |
       sudo  docker build -t my-java-app1 .
       sudo docker run -d -p 8080:8080 my-java-app1

