name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id=$AWS_ACCESS_KEY" >> ~/.aws/credentials
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          chmod 600 ~/.aws/credentials

      - name: Deploy to EC2
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
          ssh -i ~/.ssh/test.pem ec2-user@52.91.87.1 "docker stop my-java-app && docker rm my-java-app || true"
          ssh -i ~/.ssh/test.pem ec2-user@52.91.87.1 "docker run -d -p 8080:8080 --name my-java-app my-java-app:tag"
